name: Test

on:
    push:
        branches:
            - master
            - sauce-labs
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                include:
                    - node-version: 14.x
                      target: chrome
                      type: expectation
                    - node-version: 14.x
                      target: chrome
                      type: integration
                    - node-version: 14.x
                      target: chrome-legacy
                      type: expectation
                    - node-version: 14.x
                      target: chromium
                      type: memory
                    - node-version: 14.x
                      target: edge
                      type: expectation
                    - node-version: 14.x
                      target: edge
                      type: integration
                    - node-version: 14.x
                      target: edge-legacy
                      type: expectation
                    - node-version: 14.x
                      target: firefox
                      type: expectation
                    - node-version: 14.x
                      target: firefox
                      type: integration
                    - node-version: 14.x
                      target: node
                      type: integration
                    - node-version: 14.x
                      target: safari
                      type: integration
                    - node-version: 14.x
                      target: safari-legacy
                      type: expectation
                node-version: [14.x]
                target: [chrome, firefox]
                type: [unit]
            max-parallel: 3

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Cache node modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install dependencies
              run: npm ci

            - env:
                  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
                  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
                  TARGET: ${{ matrix.target }}
                  TYPE: ${{ matrix.type }}
              name: Run ${{ matrix.type }} tests
              run: npm test
